version: '3.7'
services:
  clickhouse:
    image: yandex/clickhouse-server:21.5.5.12-alpine
    volumes:
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    ulimits:
      nofile: 262144
    ports:
      - 8123:8123
    env_file:
      - .env
  api:
    build: ./
    depends_on:
      - clickhouse
    ports:
      - 3030:3030
    env_file:
      - .env